### PR TITLE
Rewriting characters.yml

### PR DESCRIPTION
**Pull request by devoxel**
Here's the big pull request.

There's a ton of stuff, so we'll have to take time to diff the files and make them work properly.

## Summary of changes:
- Character Schema changed. Data is now hashed
- Changes to character.html, to suit the data change
- Polished up README
- Added [humans.txt](humanstxt.org)

## Important notes
- Character image files are now accessed directly by name, so names have to match. We should rethink this after the merge.
- Generation time will be a good bit longer now, since each character page requires a full look through the characters.yml file. This should be fixable, since the data should be accessible through it's hash, but I couldn't get it to work yet. I will add this to issues after the merge and certainly make efforts to fix it.

## Important Design Decision Going Forward

Should we statically declare each character, as we're doing now, or build a generation script that bases it's data on characters.yml? 

I think the former makes more sense personally, since really it's only a one time task and the files are very easy to write.

### CODE REVIEW

**Comment by HappyZombies** [comment]
I have added some very simple python scripts to auto generate files, mostly for the characters. I like the changes you have made to the default layouts and the Readme.md looks much better! I will merge after fixing the conflicts and change a few things. 

I believe that we should keep videos.yml and character.yml (their name and color) on a separate file. I believe it will be easier to loop through videos.yml...but of course, if you know how to optimize it then by all means. Do your magic. 

Cool stuff man. I will merge it soon.

**Comment by HappyZombies** [comment]
Actually, if you can. Go see what I have done, I will be combining the code accordingly.

**Comment by devoxel** [comment]
Performance wise them methods I'm using to generate the characters isn't going to change if we move the videos to a separate file. 

This is because I'm using hashes values to grab the content for each character, so that's low impact. What's high impact is the initial loop that checks if the `page.name` value matches a value in `site.data.characters`.

Worst case performace it's:
    f(n) = O(n^2)

That is bad, but remember that jekyll is static generation, so performance is only generative and only on our end.

I'll take another look at the Liquid engine documentation and see if there's a way to directly access the data, but I think it does make more sense to represent the data in this way.

**Comment by HappyZombies** [comment]
Alright, thanks for the explanation.

**Comment by HappyZombies** [comment]
Aaron, file `footer_image.html` has to be very specific. The for loop must go after the `<li>` and the loop must before the `</li>`. It's weird, but the CSS is made very specifically to get this effect. 

[This is how it looked before.](http://i.imgur.com/8Rq9Mx4.png)

[How it looks now after putting the loops after `<li>`.](http://i.imgur.com/uCg6pOZ.png)

Also I noticed you would put </img> end tag,  does not need an and end tag. In fact, it doesn't even have an [end tag](http://www.w3schools.com/tags/tag_img.asp) (for HTML that is). Removing </img> also fixes the problem of the images getting [this weird blue line next to them](http://i.imgur.com/iyavMvF.png)....actually after much digging around the problem still persisted. 
I found that the reason those blue lines were occuring was because the `href="{{site.baseurl}}/{{character[0] | downcase}}"` you added an extra '/' . I just removed the slash. This was done on index.html and it fixed the issue. 

....Okay that's odd, I added the slash again and the problem was gone...now I'm not sure what the problem was...oh well, it was fixed none the less. (I still think it was the </img>)

Anyhow, I updated characters.yml with all the characters, they just don't have the links for the videos. (Only Mario and Luigi do). It was a simple copy and paste, since I had the python script generate the other names for me :P 

Merging it soon!

**Comment by HappyZombies** [comment]
Ugh what the heck, I thought I followed the instructions accordingly...oh well, I wanted to merge this request after editing some files, but at least I got all the stuff you add/fixed. I'll be closing this. :(

**Pull request closed without merging**
